apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: canary-staging
  namespace: staging
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/app-root: /
spec:
  rules:
  - host: canary-staging.dev.argoproj.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: canary-staging
            port:
              name: http
