apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base
- canary-analysis-step-success.yaml
- analysis-http-benchmark-single.yaml
# Blue-Green Rollout
- bluegreen-rollout.yaml
- bluegreen-service.yaml
- bluegreen-preview-service.yaml
- bluegreen-ingress.yaml
- bluegreen-preview-ingress.yaml
